using System;
using System.Collections.Generic;

namespace ContextLeech.Constants;

public static class FileSystemConstants
{
    public const string ContextLeechRootDirectory = ".context-leech";
    public const string MetadataSubDirectory = "metadata";
    public const string ContextSubDirectory = "context";

    public static readonly IReadOnlySet<string> EmbeddedDirectoriesToIgnore = new HashSet<string>(StringComparer.OrdinalIgnoreCase)
    {
        ".git",
        "node_modules",
        ContextLeechRootDirectory
    };

    public static readonly IReadOnlySet<string> EmbeddedTextFilesExtensions = new HashSet<string>(StringComparer.OrdinalIgnoreCase)
    {
        ".babelrc",
        ".bash",
        ".bat",
        ".browser",
        ".browserslistrc",
        ".cmd",
        ".conf",
        ".config",
        ".coverage",
        ".coveragexml",
        ".cs",
        ".cshtml",
        ".csproj",
        ".css",
        ".csv",
        ".dockerfile",
        ".Dockerfile",
        ".dockerignore",
        ".DotSettings",
        ".dtd",
        ".editorconfig",
        ".env",
        ".eslintrc",
        ".exclude",
        ".gitattributes",
        ".gitignore",
        ".globalconfig",
        ".gql",
        ".graphql",
        ".html",
        ".htmlhintrc",
        ".http",
        ".idl",
        ".imports",
        ".include",
        ".inf",
        ".ini",
        ".js",
        ".jshintrc",
        ".json",
        ".jsx",
        ".jwt",
        ".less",
        ".log",
        ".manifest",
        ".md",
        ".npmrc",
        ".nuspec",
        ".nvmrc",
        ".passwords",
        ".pkgdef",
        ".prettierrc",
        ".properties",
        ".props",
        ".proto",
        ".ps1",
        ".psd1",
        ".psm1",
        ".pubxml",
        ".razor",
        ".rc",
        ".rest",
        ".resx",
        ".rsp",
        ".ruleset",
        ".runsettings",
        ".sass",
        ".scss",
        ".semgrepignore",
        ".settings",
        ".sh",
        ".sln",
        ".snippet",
        ".sql",
        ".stylelintrc",
        ".t4",
        ".targets",
        ".template",
        ".test",
        ".testconfig",
        ".testrunconfig",
        ".testsettings",
        ".toml",
        ".transform",
        ".trivyignore",
        ".ts",
        ".tsv",
        ".tsx",
        ".tt",
        ".ttinclude",
        ".txt",
        ".user",
        ".vsixmanifest",
        ".vsmdi",
        ".vstemplate",
        ".webmanifest",
        ".wsdl",
        ".xaml",
        ".xlf",
        ".xml",
        ".xsd",
        ".xsl",
        ".xslt",
        ".yaml",
        ".yarnrc",
        ".yml"
    };
}
